//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.dataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class caFaces
    {
        public int id { get; set; }
        public System.DateTime fIns { get; set; }
        public int idUsr { get; set; }
        public byte[] face { get; set; }
        public bool active { get; set; }
    
        public virtual caUsers caUsers { get; set; }
    }
}
