//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.dataBases
{
    using System;
    using System.Collections.Generic;
    
    public partial class caPerson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public caPerson()
        {
            this.caUsers = new HashSet<caUsers>();
        }
    
        public int id { get; set; }
        public System.DateTime fIns { get; set; }
        public string ap1 { get; set; }
        public string ap2 { get; set; }
        public string names { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caUsers> caUsers { get; set; }
    }
}
