//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.dataBases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdFaceRepositoryEntities : DbContext
    {
        public bdFaceRepositoryEntities()
            : base("name=bdFaceRepositoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<caFaces> caFaces { get; set; }
        public virtual DbSet<caPerson> caPerson { get; set; }
        public virtual DbSet<caUsers> caUsers { get; set; }
    }
}
